# Generated by Django 2.2.7 on 2019-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaandu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=20, unique=True)),
                ('Monday', models.BooleanField()),
                ('Monday_time', models.IntegerField(default=24)),
                ('Tuesday', models.BooleanField()),
                ('Tuesday_time', models.IntegerField(default=24)),
                ('Wednesday', models.BooleanField()),
                ('Wednesday_time', models.IntegerField(default=24)),
                ('Thursday', models.BooleanField()),
                ('Thursday_time', models.IntegerField(default=24)),
                ('Friday', models.BooleanField()),
                ('Friday_time', models.IntegerField(default=24)),
                ('Saturday', models.BooleanField()),
                ('Saturday_time', models.IntegerField(default=24)),
            ],
        ),
    ]
