# Generated by Django 2.2.7 on 2019-11-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_slots', '0002_auto_20191108_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Friday_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Monday_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Saturday_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Thursday_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Tuesday_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slot',
            name='Wednesday_time',
            field=models.IntegerField(default=24),
        ),
    ]
