# Generated by Django 2.2.7 on 2019-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_slots', '0003_auto_20191108_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
